a=input('Digite algo: ')
b=input('O tipo primitivo desse valor é: ',type(a))
c=input('Só tem espaço? ', a.isspace())
d=input('É um número? ', a.isnumeric())
e=input('É alfabético? ', a.isalpha())
f=input('É alfanumérico? ', a.isalnum())
g=input('Está em maiúscula? ', a.isupper())
h=input('Está em minúscula? ', a.islower())
i=input('Está capitalizada? ', a.istitle())
print(''.format(a, b, c, d, e, f, g, h, i))